---
title: "Visualizing Regression"
author: "Robert Horton"
date: "February 7, 2015"
runtime: shiny
output: ioslides_presentation
---

## Linear Regression

Fitting a regression line by Ordinary Least Squares (OLS) is done by minimizing the sum of squared errors.

$$
y = mx + b
$$

## Optimizing Slope and Intercept
```{r get_points, echo=FALSE}
set.seed(103)
N <- 20
SLOPE <- 1.5
INTERCEPT <- 12
x <- runif(N, 0, 100)
y <- SLOPE * x + INTERCEPT + rnorm(N, 0, 10)
```
<table><tr><td>
```{r echo = FALSE}
# http://shiny.rstudio.com/articles/interactive-docs.html
fit <- lm(y ~ x)
fitted_intercept <- coef(fit)[1]
fitted_slope <- coef(fit)[2]
sliderInput("m", "slope:", min = (SLOPE-2), max = (SLOPE+2), value = fitted_slope)
sliderInput("b", "y-intercept:", min = -10, max = 100, value = fitted_intercept)
```
</td><td>

```{r echo=FALSE}
renderPlot({
    b <- as.numeric(input$b)
    m <- as.numeric(input$m)
    plot(x, y, pch=16, xlim=c(0,100), ylim=c(0,max(y)))
    abline(b, m, col="yellow")
    predictions <- m * x + b
    residuals <- y - predictions
    for (i in seq_along(x))
        lines(c(x[i],x[i]), c(y[i],predictions[i]), col="#ff8888")
    sse <- round(sum(residuals^2),1)
    text(90,10,paste("SSE:", sse))
})
```
</td></tr></table>


