---
title: "Probability Distribution Demos"
author: "Robert Horton"
date: "December 31, 2014"
runtime: shiny
output: ioslides_presentation
---

## The Normal Curve

Mean controls the position of the peak and standard deviation controls the width.

<table><tr><td>
```{r echo = FALSE}
# http://shiny.rstudio.com/articles/interactive-docs.html
sliderInput("m", "Mean:", min = -10, max = 10, value = 0)
```
</td><td>
```{r echo=FALSE}
sliderInput("s", "Standard deviation:", min = 0.1, max = 5, value = 1)
```
</tr></table>
```{r echo=FALSE}
renderPlot({
    x <- seq(-10, 10, by=0.1)
    plot(x, dnorm(x, mean=as.numeric(input$m), sd=as.numeric(input$s)), 
                    type="l", col="red", ylab="density")
})
```

## Alpha and Beta

<table><tr><td>
```{r echo = FALSE}
# http://shiny.rstudio.com/articles/interactive-docs.html
sliderInput("m1", "Mean 1:", min = -10, max = 10, value = -2)
```
</td><td>
```{r echo=FALSE}
sliderInput("s1", "Std dev 1:", min = 0.1, max = 5, value = 1)
```
</td></tr>
<tr><td>
```{r echo = FALSE}
# http://shiny.rstudio.com/articles/interactive-docs.html
sliderInput("crit_val", "critical value:", min = -10, max = 10, value = 0)
```
</td><td>
```{r echo=FALSE}
```
</td></tr>
<tr><td>
```{r echo = FALSE}
# http://shiny.rstudio.com/articles/interactive-docs.html
sliderInput("m2", "Mean 2:", min = -10, max = 10, value = 2)
```
</td><td>
```{r echo=FALSE}
sliderInput("s2", "Std dev 2:", min = 0.1, max = 5, value = 2)
```
</td></tr>
</table>
```{r echo=FALSE}
renderPlot({
    x <- seq(-10, 10, by=0.1)
    y1 <- dnorm(x, mean=as.numeric(input$m1), sd=as.numeric(input$s1))
    y2 <- dnorm(x, mean=as.numeric(input$m2), sd=as.numeric(input$s2))
    plot(x, pmax(y1, y2), type="n")
    lines(x, y1, lwd=2, col="blue", ylab="density")
    lines(x, y2, lwd=2, col="green", ylab="density")
    p1x <- x[x >= input$crit_val]
    p1y <- dnorm(p1x, mean=as.numeric(input$m1), sd=as.numeric(input$s1))
    p2x <- x[x <= input$crit_val]
    p2y <- dnorm(p2x, mean=as.numeric(input$m2), sd=as.numeric(input$s2))
    polygon(c(input$crit_val, p1x), c(0, p1y), density=15, col="blue")
    polygon(c(p2x, input$crit_val), c(p2y, 0), density=15, col="green")
    abline(v=as.numeric(input$crit_val), lty=2, lwd=2, col="red")
})
```

