---
title: "Automated Feature Selection"
author: "Bob Horton"
date: "April 26, 2015"
output: html_document
---

## Non-informative columns

```{r fake_data}
N <- 20000

w <- rnorm(N)
x <- rnorm(N)
y <- 10 + 1.1 * w + 2.2 * x + rnorm(N)
df1 <- data.frame( y, w, x )

for (bogus in 1:10){
  df1[[sprintf("bogus_cat%02i", bogus)]] <- sample(LETTERS, N, replace=T)
	df1[[sprintf("bogus_num%02i", bogus)]] <- runif(N, max=runif(N, max=10))
}

fit <- lm( y ~ w + x )
summary(fit)
```

### 
```{r automatic_main_effects}
get_all_inputs_formula <- function(df, outcome_col, op="+"){
	inputs <- names(df)[names(df) != outcome_col]
	as.formula(paste('y', paste(inputs, collapse=op), sep="~"))
}

library(MASS)

fit1 <- lm(y ~ w + x + bogus_cat01 + bogus_num01 + bogus_cat02 + bogus_num02 + bogus_cat03 + bogus_num03 + bogus_cat04 + bogus_num04 + bogus_cat05 + bogus_num05 + bogus_cat06 + bogus_num06 + bogus_cat07 + bogus_num07 + bogus_cat08 + bogus_num08 + bogus_cat09 + bogus_num09 + bogus_cat10 + bogus_num10,
          data=df1)
fit1step <- stepAIC(fit1, direction="backward")

summary(fit1step)
```

## Add columns with redundant information
```{r}
X <- cbind(w, x)

in_cols <- 2
out_cols <- 6
M <- matrix( runif( in_cols * out_cols ), ncol=out_cols )

XX <- X %*% M + 0.1 * runif( N * out_cols )

colnames(XX) <- paste0("XX", 1:out_cols)

df2 <- as.data.frame( cbind(y, w, x, XX) )

# paste('y', paste(names(df2)[-1], collapse=" + "), sep=" ~ ")

fit2 <- lm(y ~ w + x + XX1 + XX2 + XX3 + XX4 + XX5 + XX6, data=df2)


stepAIC(fit2, direction="backward")


fit3 <- lm(y ~ XX1 + XX2 + XX3 + XX4 + XX5 + XX6, data=df2)

# paste('y', paste(names(df2)[-1], collapse=" * "), sep=" ~ ")

fit4 <- lm(y ~ w * x * XX1 * XX2 * XX3 * XX4 * XX5 * XX6, data=df2)

# fit4step <- stepAIC(fit4)

```

```
> fit4step <- stepAIC(fit4)
> summary(fit4step)

Call:
lm(formula = y ~ w + x + XX1 + XX2 + XX3 + XX4 + XX5 + XX6 + 
    w:x + w:XX1 + x:XX1 + w:XX2 + x:XX2 + XX1:XX2 + w:XX3 + x:XX3 + 
    XX1:XX3 + XX2:XX3 + w:XX4 + x:XX4 + XX1:XX4 + XX2:XX4 + XX3:XX4 + 
    w:XX5 + x:XX5 + XX1:XX5 + XX2:XX5 + XX3:XX5 + XX4:XX5 + w:XX6 + 
    x:XX6 + XX1:XX6 + XX2:XX6 + XX3:XX6 + XX4:XX6 + XX5:XX6 + 
    w:x:XX1 + w:x:XX2 + w:XX1:XX2 + x:XX1:XX2 + w:x:XX3 + w:XX1:XX3 + 
    x:XX1:XX3 + w:XX2:XX3 + x:XX2:XX3 + XX1:XX2:XX3 + w:x:XX4 + 
    w:XX1:XX4 + x:XX1:XX4 + w:XX2:XX4 + x:XX2:XX4 + XX1:XX2:XX4 + 
    w:XX3:XX4 + x:XX3:XX4 + XX1:XX3:XX4 + XX2:XX3:XX4 + w:x:XX5 + 
    w:XX1:XX5 + x:XX1:XX5 + w:XX2:XX5 + x:XX2:XX5 + XX1:XX2:XX5 + 
    w:XX3:XX5 + x:XX3:XX5 + XX1:XX3:XX5 + XX2:XX3:XX5 + w:XX4:XX5 + 
    x:XX4:XX5 + XX1:XX4:XX5 + XX2:XX4:XX5 + XX3:XX4:XX5 + w:x:XX6 + 
    w:XX1:XX6 + x:XX1:XX6 + w:XX2:XX6 + x:XX2:XX6 + XX1:XX2:XX6 + 
    w:XX3:XX6 + x:XX3:XX6 + XX1:XX3:XX6 + XX2:XX3:XX6 + w:XX4:XX6 + 
    x:XX4:XX6 + XX1:XX4:XX6 + XX2:XX4:XX6 + XX3:XX4:XX6 + w:XX5:XX6 + 
    x:XX5:XX6 + XX1:XX5:XX6 + XX2:XX5:XX6 + XX3:XX5:XX6 + XX4:XX5:XX6 + 
    w:x:XX1:XX2 + w:x:XX1:XX3 + w:x:XX2:XX3 + w:XX1:XX2:XX3 + 
    x:XX1:XX2:XX3 + w:x:XX1:XX4 + w:x:XX2:XX4 + w:XX1:XX2:XX4 + 
    x:XX1:XX2:XX4 + w:x:XX3:XX4 + w:XX1:XX3:XX4 + x:XX1:XX3:XX4 + 
    w:XX2:XX3:XX4 + x:XX2:XX3:XX4 + XX1:XX2:XX3:XX4 + w:x:XX1:XX5 + 
    w:x:XX2:XX5 + w:XX1:XX2:XX5 + x:XX1:XX2:XX5 + w:x:XX3:XX5 + 
    w:XX1:XX3:XX5 + x:XX1:XX3:XX5 + w:XX2:XX3:XX5 + x:XX2:XX3:XX5 + 
    XX1:XX2:XX3:XX5 + w:x:XX4:XX5 + w:XX1:XX4:XX5 + x:XX1:XX4:XX5 + 
    w:XX2:XX4:XX5 + x:XX2:XX4:XX5 + XX1:XX2:XX4:XX5 + w:XX3:XX4:XX5 + 
    x:XX3:XX4:XX5 + XX1:XX3:XX4:XX5 + XX2:XX3:XX4:XX5 + w:x:XX1:XX6 + 
    w:x:XX2:XX6 + w:XX1:XX2:XX6 + x:XX1:XX2:XX6 + w:x:XX3:XX6 + 
    w:XX1:XX3:XX6 + x:XX1:XX3:XX6 + w:XX2:XX3:XX6 + x:XX2:XX3:XX6 + 
    XX1:XX2:XX3:XX6 + w:x:XX4:XX6 + w:XX1:XX4:XX6 + x:XX1:XX4:XX6 + 
    w:XX2:XX4:XX6 + x:XX2:XX4:XX6 + XX1:XX2:XX4:XX6 + w:XX3:XX4:XX6 + 
    x:XX3:XX4:XX6 + XX1:XX3:XX4:XX6 + XX2:XX3:XX4:XX6 + w:x:XX5:XX6 + 
    w:XX1:XX5:XX6 + x:XX1:XX5:XX6 + w:XX2:XX5:XX6 + x:XX2:XX5:XX6 + 
    XX1:XX2:XX5:XX6 + w:XX3:XX5:XX6 + x:XX3:XX5:XX6 + XX1:XX3:XX5:XX6 + 
    XX2:XX3:XX5:XX6 + w:XX4:XX5:XX6 + x:XX4:XX5:XX6 + XX1:XX4:XX5:XX6 + 
    XX2:XX4:XX5:XX6 + XX3:XX4:XX5:XX6 + w:x:XX1:XX2:XX3 + w:x:XX1:XX2:XX4 + 
    w:x:XX1:XX3:XX4 + w:x:XX1:XX2:XX5 + w:x:XX1:XX3:XX5 + w:x:XX2:XX3:XX5 + 
    w:XX1:XX2:XX3:XX5 + x:XX1:XX2:XX3:XX5 + w:x:XX1:XX4:XX5 + 
    w:x:XX2:XX4:XX5 + w:XX1:XX2:XX4:XX5 + x:XX1:XX2:XX4:XX5 + 
    w:x:XX3:XX4:XX5 + w:XX1:XX3:XX4:XX5 + x:XX1:XX3:XX4:XX5 + 
    XX1:XX2:XX3:XX4:XX5 + w:x:XX1:XX2:XX6 + w:x:XX1:XX3:XX6 + 
    w:x:XX2:XX3:XX6 + w:XX1:XX2:XX3:XX6 + x:XX1:XX2:XX3:XX6 + 
    w:x:XX1:XX4:XX6 + w:x:XX2:XX4:XX6 + w:XX1:XX2:XX4:XX6 + x:XX1:XX2:XX4:XX6 + 
    w:XX1:XX3:XX4:XX6 + w:XX2:XX3:XX4:XX6 + XX1:XX2:XX3:XX4:XX6 + 
    w:x:XX1:XX5:XX6 + w:x:XX2:XX5:XX6 + w:XX1:XX2:XX5:XX6 + x:XX1:XX2:XX5:XX6 + 
    w:XX1:XX3:XX5:XX6 + w:XX2:XX3:XX5:XX6 + XX1:XX2:XX3:XX5:XX6 + 
    w:x:XX4:XX5:XX6 + w:XX1:XX4:XX5:XX6 + x:XX1:XX4:XX5:XX6 + 
    w:XX2:XX4:XX5:XX6 + x:XX2:XX4:XX5:XX6 + XX1:XX2:XX4:XX5:XX6 + 
    XX1:XX3:XX4:XX5:XX6 + XX2:XX3:XX4:XX5:XX6 + w:x:XX1:XX2:XX3:XX5 + 
    w:x:XX1:XX2:XX4:XX5 + w:x:XX1:XX3:XX4:XX5 + w:x:XX1:XX2:XX3:XX6 + 
    w:x:XX1:XX2:XX4:XX6 + w:x:XX1:XX2:XX5:XX6 + w:x:XX1:XX4:XX5:XX6 + 
    w:XX1:XX2:XX4:XX5:XX6 + x:XX1:XX2:XX4:XX5:XX6 + XX1:XX2:XX3:XX4:XX5:XX6, 
    data = df2)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.9820 -0.6648  0.0019  0.6748  3.8892 

Coefficients:
                          Estimate Std. Error t value Pr(>|t|)    
(Intercept)               10.00277    0.06030 165.871  < 2e-16 ***
w                          0.82796    0.78781   1.051 0.293288    
x                          1.77739    0.58992   3.013 0.002591 ** 
XX1                       -1.68585    1.22381  -1.378 0.168361    
XX2                       -1.08101    1.20214  -0.899 0.368534    
XX3                        1.85302    0.91792   2.019 0.043530 *  
XX4                        0.71030    1.23283   0.576 0.564516    
XX5                       -0.77605    0.79902  -0.971 0.331435    
XX6                        0.35615    1.05651   0.337 0.736047    
w:x                        0.08021    1.16317   0.069 0.945027    
w:XX1                    -18.02882   16.37342  -1.101 0.270865    
x:XX1                    -13.34472   11.96645  -1.115 0.264788    
w:XX2                    -12.07064   15.75021  -0.766 0.443460    
x:XX2                    -16.10808   10.68390  -1.508 0.131648    
XX1:XX2                   29.01314   20.90001   1.388 0.165095    
w:XX3                     16.48390   11.55217   1.427 0.153622    
x:XX3                     13.78447    6.61120   2.085 0.037080 *  
XX1:XX3                   -2.08767   15.27077  -0.137 0.891261    
XX2:XX3                    6.34024   13.36916   0.474 0.635331    
w:XX4                      0.38729   15.78117   0.025 0.980421    
x:XX4                      1.81523   11.74425   0.155 0.877167    
XX1:XX4                    0.56852   23.13767   0.025 0.980397    
XX2:XX4                   10.15275   19.26443   0.527 0.598185    
XX3:XX4                  -24.09064   15.16267  -1.589 0.112119    
w:XX5                     -0.35517    6.51014  -0.055 0.956493    
x:XX5                     -3.23645    6.79740  -0.476 0.633987    
XX1:XX5                   16.25184   15.34699   1.059 0.289631    
XX2:XX5                   -5.11499   15.86291  -0.322 0.747116    
XX3:XX5                    7.51416   12.68489   0.592 0.553609    
XX4:XX5                  -12.15147   13.11220  -0.927 0.354078    
w:XX6                      1.41078   11.63218   0.121 0.903468    
x:XX6                      6.22340    9.39736   0.662 0.507819    
XX1:XX6                   -9.92241   19.99981  -0.496 0.619812    
XX2:XX6                   -4.45240   16.56442  -0.269 0.788092    
XX3:XX6                  -14.70695   13.20910  -1.113 0.265552    
XX4:XX6                   24.26888   14.05036   1.727 0.084133 .  
XX5:XX6                    0.37469    9.84774   0.038 0.969650    
w:x:XX1                  -12.34707   20.44027  -0.604 0.545813    
w:x:XX2                    9.91696   16.90684   0.587 0.557503    
w:XX1:XX2                221.66082  264.19281   0.839 0.401473    
x:XX1:XX2                158.01225  162.15889   0.974 0.329856    
w:x:XX3                    4.87588    5.42721   0.898 0.368976    
w:XX1:XX3                 77.18966  173.17279   0.446 0.655792    
x:XX1:XX3                 44.99335   82.65907   0.544 0.586224    
w:XX2:XX3               -145.06461  127.57439  -1.137 0.255511    
x:XX2:XX3                -53.87410   54.69939  -0.985 0.324679    
XX1:XX2:XX3             -145.75543  133.18349  -1.094 0.273795    
w:x:XX4                  -10.80491   13.24485  -0.816 0.414635    
w:XX1:XX4               -249.96167  299.03661  -0.836 0.403227    
x:XX1:XX4               -111.08585  209.93347  -0.529 0.596709    
w:XX2:XX4                 83.21926  218.34605   0.381 0.703107    
x:XX2:XX4                -12.36015  144.50222  -0.086 0.931836    
XX1:XX2:XX4              -67.69030  236.60939  -0.286 0.774816    
w:XX3:XX4                 30.22402  162.47034   0.186 0.852425    
x:XX3:XX4                 -2.05740   80.25112  -0.026 0.979547    
XX1:XX3:XX4              -14.68381  221.83045  -0.066 0.947224    
XX2:XX3:XX4              145.86552  149.40032   0.976 0.328908    
w:x:XX5                    3.29294    1.70756   1.928 0.053814 .  
w:XX1:XX5                165.24955  107.44882   1.538 0.124080    
x:XX1:XX5                177.65988  119.58962   1.486 0.137406    
w:XX2:XX5                 24.17789   85.80338   0.282 0.778113    
x:XX2:XX5                  9.47012   97.44635   0.097 0.922582    
XX1:XX2:XX5             -178.16565  267.08175  -0.667 0.504727    
w:XX3:XX5                -77.52042   48.61369  -1.595 0.110813    
x:XX3:XX5                -60.94098   41.28615  -1.476 0.139943    
XX1:XX3:XX5              -97.26338  222.59953  -0.437 0.662157    
XX2:XX3:XX5              112.15940  187.32937   0.599 0.549361    
w:XX4:XX5                -29.29449   42.08327  -0.696 0.486369    
x:XX4:XX5                -32.18641   58.72374  -0.548 0.583630    
XX1:XX4:XX5               99.10304  248.23836   0.399 0.689731    
XX2:XX4:XX5             -164.35681  198.34098  -0.829 0.407308    
XX3:XX4:XX5              124.58943  194.78511   0.640 0.522424    
w:x:XX6                   -0.51458    5.62581  -0.091 0.927122    
w:XX1:XX6               -166.26673  220.71786  -0.753 0.451279    
x:XX1:XX6               -198.36925  165.85160  -1.196 0.231686    
w:XX2:XX6                -54.10384  151.90664  -0.356 0.721721    
x:XX2:XX6                -36.76007  107.08240  -0.343 0.731386    
XX1:XX2:XX6               57.97621  223.56019   0.259 0.795382    
w:XX3:XX6                 96.08576  106.87787   0.899 0.368651    
x:XX3:XX6                 60.17405   59.03398   1.019 0.308067    
XX1:XX3:XX6              100.91110  197.94906   0.510 0.610209    
XX2:XX3:XX6               28.56095  134.46706   0.212 0.831796    
w:XX4:XX6                 53.26057   82.47361   0.646 0.518423    
x:XX4:XX6                102.64884   78.87941   1.301 0.193158    
XX1:XX4:XX6              246.40728  257.39742   0.957 0.338426    
XX2:XX4:XX6              -27.93313  162.89325  -0.171 0.863847    
XX3:XX4:XX6             -233.12053  170.59184  -1.367 0.171785    
w:XX5:XX6                 -1.52012   17.96006  -0.085 0.932550    
x:XX5:XX6                -11.10572   26.91539  -0.413 0.679892    
XX1:XX5:XX6              -89.26543  189.05609  -0.472 0.636815    
XX2:XX5:XX6               51.83106  148.57273   0.349 0.727198    
XX3:XX5:XX6              -13.96801  123.72177  -0.113 0.910112    
XX4:XX5:XX6               17.28007   65.13632   0.265 0.790788    
w:x:XX1:XX2              -14.48996   46.53765  -0.311 0.755530    
w:x:XX1:XX3               -1.14439   17.38218  -0.066 0.947508    
w:x:XX2:XX3               16.51477   13.37082   1.235 0.216795    
w:XX1:XX2:XX3           -135.46696  136.68034  -0.991 0.321638    
x:XX1:XX2:XX3            -43.79719   40.22924  -1.089 0.276304    
w:x:XX1:XX4              119.22708  120.78267   0.987 0.323596    
w:x:XX2:XX4               13.11837   53.99681   0.243 0.808049    
w:XX1:XX2:XX4              9.39258  401.36232   0.023 0.981330    
x:XX1:XX2:XX4            194.97347  177.37250   1.099 0.271680    
w:x:XX3:XX4              -76.06082   42.91721  -1.772 0.076365 .  
w:XX1:XX3:XX4            433.01735  314.80845   1.375 0.168994    
x:XX1:XX3:XX4            169.65258  106.38508   1.595 0.110795    
w:XX2:XX3:XX4           -119.77839  138.93126  -0.862 0.388620    
x:XX2:XX3:XX4           -111.07044   49.40546  -2.248 0.024578 *  
XX1:XX2:XX3:XX4         -153.01758   93.32415  -1.640 0.101097    
w:x:XX1:XX5              -18.85564   11.60058  -1.625 0.104092    
w:x:XX2:XX5               16.33747    7.38553   2.212 0.026972 *  
w:XX1:XX2:XX5           -303.08709  298.75750  -1.014 0.310360    
x:XX1:XX2:XX5           -190.56058  281.83835  -0.676 0.498963    
w:x:XX3:XX5               -4.69554    3.00829  -1.561 0.118571    
w:XX1:XX3:XX5            291.70825  166.33018   1.754 0.079482 .  
x:XX1:XX3:XX5            140.18279  122.09303   1.148 0.250915    
w:XX2:XX3:XX5            -70.66243   99.52353  -0.710 0.477708    
x:XX2:XX3:XX5            -74.90937   78.27669  -0.957 0.338588    
XX1:XX2:XX3:XX5          350.80686  288.42019   1.216 0.223883    
w:x:XX4:XX5               -4.35177    2.89694  -1.502 0.133062    
w:XX1:XX4:XX5           -456.30586  263.63134  -1.731 0.083494 .  
x:XX1:XX4:XX5           -641.07522  369.28092  -1.736 0.082578 .  
w:XX2:XX4:XX5            185.22681  115.34125   1.606 0.108311    
x:XX2:XX4:XX5            143.69171  164.02324   0.876 0.381016    
XX1:XX2:XX4:XX5          693.92744  591.66658   1.173 0.240876    
w:XX3:XX4:XX5             60.66513   91.06455   0.666 0.505306    
x:XX3:XX4:XX5            221.28891  122.24593   1.810 0.070281 .  
XX1:XX3:XX4:XX5         -584.69026  549.49671  -1.064 0.287320    
XX2:XX3:XX4:XX5         -111.64022  257.41276  -0.434 0.664510    
w:x:XX1:XX6              -82.64230   74.27674  -1.113 0.265882    
w:x:XX2:XX6               -3.75442   34.99941  -0.107 0.914575    
w:XX1:XX2:XX6            200.68979  322.48794   0.622 0.533740    
x:XX1:XX2:XX6            -26.97436  172.15425  -0.157 0.875493    
w:x:XX3:XX6               43.53834   25.30155   1.721 0.085307 .  
w:XX1:XX3:XX6           -205.51872  224.62176  -0.915 0.360227    
x:XX1:XX3:XX6           -103.42122   91.76703  -1.127 0.259757    
w:XX2:XX3:XX6             59.79275  101.64533   0.588 0.556372    
x:XX2:XX3:XX6             99.16743   47.08116   2.106 0.035190 *  
XX1:XX2:XX3:XX6            8.24424  109.69146   0.075 0.940089    
w:x:XX4:XX6               -0.51454    8.04542  -0.064 0.949007    
w:XX1:XX4:XX6           -189.22772  279.04327  -0.678 0.497697    
x:XX1:XX4:XX6           -106.69278  179.39545  -0.595 0.552027    
w:XX2:XX4:XX6             92.48506  102.46552   0.903 0.366751    
x:XX2:XX4:XX6             87.73571   69.08908   1.270 0.204138    
XX1:XX2:XX4:XX6         -353.15726  176.96081  -1.996 0.045982 *  
w:XX3:XX4:XX6            -62.22909   85.80179  -0.725 0.468298    
x:XX3:XX4:XX6            -88.05295   49.47575  -1.780 0.075137 .  
XX1:XX3:XX4:XX6          354.45904  200.64727   1.767 0.077314 .  
XX2:XX3:XX4:XX6           19.11101   81.17419   0.235 0.813876    
w:x:XX5:XX6                1.87628    0.95846   1.958 0.050292 .  
w:XX1:XX5:XX6            262.60101  140.61408   1.868 0.061842 .  
x:XX1:XX5:XX6            500.39155  203.29402   2.461 0.013847 *  
w:XX2:XX5:XX6            -41.34007   60.42913  -0.684 0.493915    
x:XX2:XX5:XX6           -106.58663   94.89923  -1.123 0.261385    
XX1:XX2:XX5:XX6         -180.70895  442.78887  -0.408 0.683193    
w:XX3:XX5:XX6            -38.36719   45.24222  -0.848 0.396426    
x:XX3:XX5:XX6            -96.60090   63.39245  -1.524 0.127561    
XX1:XX3:XX5:XX6         -357.25174  395.97413  -0.902 0.366956    
XX2:XX3:XX5:XX6          135.37787  182.40079   0.742 0.457975    
w:XX4:XX5:XX6            -21.65961   22.79211  -0.950 0.341966    
x:XX4:XX5:XX6            -20.79711   35.80765  -0.581 0.561381    
XX1:XX4:XX5:XX6          368.82718  323.72143   1.139 0.254577    
XX2:XX4:XX5:XX6         -218.82501  128.20742  -1.707 0.087874 .  
XX3:XX4:XX5:XX6          105.07112  140.49339   0.748 0.454546    
w:x:XX1:XX2:XX3            4.86517    4.85187   1.003 0.315998    
w:x:XX1:XX2:XX4          -25.55285   12.26239  -2.084 0.037188 *  
w:x:XX1:XX3:XX4           11.74384    9.92906   1.183 0.236913    
w:x:XX1:XX2:XX5           -4.22823    8.94582  -0.473 0.636469    
w:x:XX1:XX3:XX5            6.53419    4.70783   1.388 0.165171    
w:x:XX2:XX3:XX5           -2.60142    2.81415  -0.924 0.355286    
w:XX1:XX2:XX3:XX5         17.04548   11.38778   1.497 0.134456    
x:XX1:XX2:XX3:XX5         -2.76232   11.83016  -0.233 0.815377    
w:x:XX1:XX4:XX5          -11.61147   11.44629  -1.014 0.310390    
w:x:XX2:XX4:XX5            9.42621    5.59352   1.685 0.091966 .  
w:XX1:XX2:XX4:XX5         16.43862   14.92264   1.102 0.270654    
x:XX1:XX2:XX4:XX5         26.43760   17.85495   1.481 0.138706    
w:x:XX3:XX4:XX5           -0.72777    1.67412  -0.435 0.663771    
w:XX1:XX3:XX4:XX5         -0.07283   12.30323  -0.006 0.995277    
x:XX1:XX3:XX4:XX5         10.69059   10.55150   1.013 0.310986    
XX1:XX2:XX3:XX4:XX5      -53.27177   19.33013  -2.756 0.005859 ** 
w:x:XX1:XX2:XX6            8.68098   14.02270   0.619 0.535880    
w:x:XX1:XX3:XX6          -20.67072    8.34979  -2.476 0.013310 *  
w:x:XX2:XX3:XX6            5.78967    2.71698   2.131 0.033108 *  
w:XX1:XX2:XX3:XX6         -4.21765    7.40606  -0.569 0.569033    
x:XX1:XX2:XX3:XX6         -0.66089    3.54385  -0.186 0.852063    
w:x:XX1:XX4:XX6           31.94845   15.44616   2.068 0.038618 *  
w:x:XX2:XX4:XX6          -12.86011    5.37539  -2.392 0.016748 *  
w:XX1:XX2:XX4:XX6         -8.06323   11.23112  -0.718 0.472805    
x:XX1:XX2:XX4:XX6        -17.37173    7.41427  -2.343 0.019139 *  
w:XX1:XX3:XX4:XX6        -16.06982    9.65425  -1.665 0.096022 .  
w:XX2:XX3:XX4:XX6          6.64917    3.36342   1.977 0.048066 *  
XX1:XX2:XX3:XX4:XX6       26.50396    7.84040   3.380 0.000725 ***
w:x:XX1:XX5:XX6           -2.14306    4.34573  -0.493 0.621918    
w:x:XX2:XX5:XX6           -0.06244    2.12296  -0.029 0.976535    
w:XX1:XX2:XX5:XX6         -5.89902    8.33840  -0.707 0.479294    
x:XX1:XX2:XX5:XX6         15.53287   13.05139   1.190 0.234009    
w:XX1:XX3:XX5:XX6         12.07353    6.57053   1.838 0.066147 .  
w:XX2:XX3:XX5:XX6         -3.63699    2.18719  -1.663 0.096356 .  
XX1:XX2:XX3:XX5:XX6      -15.50963   16.27422  -0.953 0.340592    
w:x:XX4:XX5:XX6           -0.19381    0.60819  -0.319 0.749983    
w:XX1:XX4:XX5:XX6        -16.50932    5.99097  -2.756 0.005862 ** 
x:XX1:XX4:XX5:XX6        -32.75740   14.10946  -2.322 0.020261 *  
w:XX2:XX4:XX5:XX6          2.41224    2.29484   1.051 0.293200    
x:XX2:XX4:XX5:XX6          3.80180    3.66736   1.037 0.299907    
XX1:XX2:XX4:XX5:XX6       21.75290   16.74766   1.299 0.194006    
XX1:XX3:XX4:XX5:XX6       24.36028   15.50652   1.571 0.116206    
XX2:XX3:XX4:XX5:XX6       -5.91936    5.08345  -1.164 0.244261    
w:x:XX1:XX2:XX3:XX5       -3.26403    0.97798  -3.338 0.000847 ***
w:x:XX1:XX2:XX4:XX5        1.98568    0.64744   3.067 0.002165 ** 
w:x:XX1:XX3:XX4:XX5        2.22496    0.65447   3.400 0.000676 ***
w:x:XX1:XX2:XX3:XX6        1.15709    0.36258   3.191 0.001419 ** 
w:x:XX1:XX2:XX4:XX6       -1.59000    0.51020  -3.116 0.001833 ** 
w:x:XX1:XX2:XX5:XX6        1.38170    0.58677   2.355 0.018544 *  
w:x:XX1:XX4:XX5:XX6       -1.73111    0.60172  -2.877 0.004020 ** 
w:XX1:XX2:XX4:XX5:XX6      0.39543    0.13418   2.947 0.003214 ** 
x:XX1:XX2:XX4:XX5:XX6      0.37729    0.14298   2.639 0.008325 ** 
XX1:XX2:XX3:XX4:XX5:XX6   -0.58341    0.19908  -2.931 0.003388 ** 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.9941 on 19784 degrees of freedom
Multiple R-squared:  0.8623,	Adjusted R-squared:  0.8608 
F-statistic: 576.1 on 215 and 19784 DF,  p-value: < 2.2e-16
```
